language: node_js
cache: yarn
node_js:
  - 7
  - 8
  - 10
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add cordova ionic
  - yarn
script:
  - yarn build
